controller_list:
  - name: fake_move_arm_controller
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
      - arm_mount_joint
